/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2021-12-18 02:45:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class questionList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1639549998000L));
    _jspx_dependants.put("jar:file:/C:/Bcle/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Bcle/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");
String cp = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>beeHelloList.jsp</title>\r\n");
      out.write("<style>\r\n");
      out.write("@import\r\n");
      out.write("\turl('https://fonts.googleapis.com/css?family=Exo+2|Noto+Sans+KR&display=swap')\r\n");
      out.write("\t;\r\n");
      out.write("\r\n");
      out.write("#content {\r\n");
      out.write("\tmargin: 5vh 34vh 5vh 30vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* .row g-0{\r\n");
      out.write("margin-bottom : 2vh;\r\n");
      out.write("border: 1px;\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write(".box {\r\n");
      out.write("\tmargin: 5vh 30vh 3vh 77%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#search form {\r\n");
      out.write("\tdisplay:flex;\r\n");
      out.write("\tmargin-bottom : 3vh;\r\n");
      out.write("\tmargin-left : 15vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".enroll {\r\n");
      out.write("\tfloat : right;\r\n");
      out.write("\tmargin-bottom : 5vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#footer {\r\n");
      out.write("\tmargin-left:35%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--  \r\n");
      out.write("\tbeeHelloList.jsp\r\n");
      out.write("\t- 동아리 내 게시판 > 가입인사 글 목록\r\n");
      out.write("-->\r\n");
      out.write("\t<div id=\"wrap\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<!-- nav 영역 -->\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 게시판 이동 영역 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<form action=\"\" name=\"categoryForm\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"categoryKey\" class=\"selectField\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"notice\">공지</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"talk\">자유글</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"greeting\">가입인사</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"review\">정모후기</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"question\">문의글</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 사이드바 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 콘텐츠 영역 -->\r\n");
      out.write("\t\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t\t<h1>문의글</h1>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"search\">\r\n");
      out.write("\t\t\t\t\t<form action=\"\" name=\"searchForm\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"searchKey\" class=\"selectField\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"subject\">제목</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"name\">작성자</option>\r\n");
      out.write("\t\t\t\t\t\t</select> <input type=\"text\" name=\"searchValue\" class=\"textField\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"검색\" class=\"btn2\" onclick=\"sendIt()\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<table id=\"questionList\" class=\"table\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>순번</th>\r\n");
      out.write("\t\t\t\t\t\t<th>글제목</th>\r\n");
      out.write("\t\t\t\t\t\t<th>작성자</th>\r\n");
      out.write("\t\t\t\t\t\t<th>작성일</th>\r\n");
      out.write("\t\t\t\t\t\t<th>답변일</th>\r\n");
      out.write("\t\t\t\t\t\t<th>처리상태</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>999</td>\r\n");
      out.write("\t\t\t\t\t\t<td>가입방법문의드립니다.</td>\r\n");
      out.write("\t\t\t\t\t\t<td>신짱구</td>\r\n");
      out.write("\t\t\t\t\t\t<td>2021-12-07</td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td>미등록</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>999</td>\r\n");
      out.write("\t\t\t\t\t\t<td>가입방법문의드립니다.</td>\r\n");
      out.write("\t\t\t\t\t\t<td>신짱구</td>\r\n");
      out.write("\t\t\t\t\t\t<td>2021-12-07</td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td>미등록</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>999</td>\r\n");
      out.write("\t\t\t\t\t\t<td>가입방법문의드립니다.</td>\r\n");
      out.write("\t\t\t\t\t\t<td>신짱구</td>\r\n");
      out.write("\t\t\t\t\t\t<td>2021-12-07</td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td>미등록</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>999</td>\r\n");
      out.write("\t\t\t\t\t\t<td>가입방법문의드립니다.</td>\r\n");
      out.write("\t\t\t\t\t\t<td>신짱구</td>\r\n");
      out.write("\t\t\t\t\t\t<td>2021-12-07</td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td>미등록</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>999</td>\r\n");
      out.write("\t\t\t\t\t\t<td>가입방법문의드립니다.</td>\r\n");
      out.write("\t\t\t\t\t\t<td>신짱구</td>\r\n");
      out.write("\t\t\t\t\t\t<td>2021-12-07</td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td>미등록</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>999</td>\r\n");
      out.write("\t\t\t\t\t\t<td>가입방법문의드립니다.</td>\r\n");
      out.write("\t\t\t\t\t\t<td>신짱구</td>\r\n");
      out.write("\t\t\t\t\t\t<td>2021-12-07</td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td>미등록</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>999</td>\r\n");
      out.write("\t\t\t\t\t\t<td>가입방법문의드립니다.</td>\r\n");
      out.write("\t\t\t\t\t\t<td>신짱구</td>\r\n");
      out.write("\t\t\t\t\t\t<td>2021-12-07</td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td>미등록</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>999</td>\r\n");
      out.write("\t\t\t\t\t\t<td>가입방법문의드립니다.</td>\r\n");
      out.write("\t\t\t\t\t\t<td>신짱구</td>\r\n");
      out.write("\t\t\t\t\t\t<td>2021-12-07</td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td>미등록</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"enroll\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary btn-sm\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\tid=\"insertBoard\" onclick=\"location.href='boardinsertform.action'\">글\r\n");
      out.write("\t\t\t\t\t\t등록</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"footer\">\r\n");
      out.write("\t\t\t\t\t<p>1 Prev 21 22 23 24 25 26 27 28 29 30 Next 54</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 푸터 영역 -->\r\n");
      out.write("\t\t<!-- 푸터 적용하니까 css가 다 엉망이 되요.. -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
