/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2021-12-21 07:43:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MainPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1639549998000L));
    _jspx_dependants.put("jar:file:/C:/Bcle/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Bcle/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    request.setCharacterEncoding("UTF-8");
    String cp = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>MainPage.jsp</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("div\r\n");
      out.write("{\r\n");
      out.write("text-align: center;}\r\n");
      out.write(".wrap\r\n");
      out.write("{\r\n");
      out.write("   min-height: 100vh;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".square\r\n");
      out.write("{\r\n");
      out.write("\tmargin-top: 0px; \r\n");
      out.write("\tmargin-left:50px; \r\n");
      out.write("\twidth : 300px;\r\n");
      out.write("  \theight: 240px;\r\n");
      out.write("  \tbackground-color: #f5d682;\r\n");
      out.write("  \tborder: 1px solid red; \r\n");
      out.write("  \tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write(".banner\r\n");
      out.write("{\r\n");
      out.write("\tmargin-top: 0px; margin-left:0px; width : 1800px;\r\n");
      out.write(" \theight: 240px;\r\n");
      out.write("  \tbackground-color: #f5d682;\r\n");
      out.write("  \tborder: 1px solid red; display: inline-block;\r\n");
      out.write("}\r\n");
      out.write(".category-square\r\n");
      out.write("{\r\n");
      out.write("\tmargin-top: 0px; width : 150px;\r\n");
      out.write("  \theight: 150px;\r\n");
      out.write("  \tbackground-color: #f5d682;\r\n");
      out.write("  \tborder: 1px solid red; display: inline-block;\r\n");
      out.write("}\r\n");
      out.write(".map\r\n");
      out.write("{\r\n");
      out.write("\tmargin-top: 0px; margin-left:0px; width : 1500px;\r\n");
      out.write(" \theight: 240px;\r\n");
      out.write("  \tbackground-color: #f5d682;\r\n");
      out.write("  \tborder: 1px solid red; display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table\r\n");
      out.write("{\r\n");
      out.write("\twidth: 1000px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write(".clubpic\r\n");
      out.write("{\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\tobject-fit: cover;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/main.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 메인화면(로그인 전) 페이지 2 -③ 카테고리 상세 페이지 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <div class=\"wrap\">\r\n");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("<div style=\"text-align: center;  margin-top: 150px;\">\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t<a href=\"\">\r\n");
      out.write("\t\t\t\t<img src=\"images/pic1.jpg\" class=\"clubpic\">\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<span>💕동아리 타이틀💕</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t<a href=\"\">\r\n");
      out.write("\t\t\t\t<img src=\"images/pic1.jpg\" class=\"clubpic\">\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<span>🐾동아리 타이틀🐾</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t<a href=\"\">\r\n");
      out.write("\t\t\t\t<img src=\"images/pic1.jpg\" class=\"clubpic\">\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<span>💕동아리 타이틀💕</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<div style=\"text-align: center;\">\r\n");
      out.write("\t<p style=\"text-align: center;\">YOUR CHOICE</p><br>\r\n");
      out.write("\t<div  class=\"banner\">\r\n");
      out.write("\t\t<a href=\"\">비클의 회원이 되시고 새로운 경험을 해보세요!(→ 클릭 시 회원가입 페이지)</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"margin: 50px;\">\r\n");
      out.write("\t<form action=\"\">\r\n");
      out.write("\t\t<input type=\"text\" placeholder=\"동아리 이름으로 검색하기\"> <input type=\"button\" value=\"검색\">\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"text-align: center;\">\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div class=\"category-square\"></div>\r\n");
      out.write("\t\t<div class=\"category-square\"></div>\r\n");
      out.write("\t\t<div class=\"category-square\"></div>\r\n");
      out.write("\t\t<div class=\"category-square\"></div>\r\n");
      out.write("\t\t<div class=\"category-square\"></div>\r\n");
      out.write("\t\t<div class=\"category-square\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div class=\"category-square\"></div>\r\n");
      out.write("\t\t<div class=\"category-square\"></div>\r\n");
      out.write("\t\t<div class=\"category-square\"></div>\r\n");
      out.write("\t\t<div class=\"category-square\"></div>\r\n");
      out.write("\t\t<div class=\"category-square\"></div>\r\n");
      out.write("\t\t<div class=\"category-square\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("\t지역\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\t<div  class=\"map\">\r\n");
      out.write("\t\t지도그림🗺🗺\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"margin-left: 300px;\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=\"\">서울</a></td>\r\n");
      out.write("\t\t\t\t<td><a href=\"\">서울</a></td>\r\n");
      out.write("\t\t\t\t<td><a href=\"\">서울</a></td>\r\n");
      out.write("\t\t\t\t<td><a href=\"\">서울</a></td>\r\n");
      out.write("\t\t\t\t<td><a href=\"\">서울</a></td>\r\n");
      out.write("\t\t\t\t<td><a href=\"\">서울</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=\"\">서울</a></td>\r\n");
      out.write("\t\t\t\t<td><a href=\"\">서울</a></td>\r\n");
      out.write("\t\t\t\t<td><a href=\"\">서울</a></td>\r\n");
      out.write("\t\t\t\t<td><a href=\"\">서울</a></td>\r\n");
      out.write("\t\t\t\t<td><a href=\"\">서울</a></td>\r\n");
      out.write("\t\t\t\t<td><a href=\"\">서울</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<div style=\"text-align: center;\">\r\n");
      out.write("\t<p>개설 예정 동아리</p><br>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t<a href=\"\">\r\n");
      out.write("\t\t\t\t<img src=\"images/pic1.jpg\" class=\"clubpic\">\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<span>💕동아리 타이틀💕</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t<a href=\"\">\r\n");
      out.write("\t\t\t\t<img src=\"images/pic1.jpg\" class=\"clubpic\">\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<span>💕동아리 타이틀💕</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t<a href=\"\">\r\n");
      out.write("\t\t\t\t<img src=\"images/pic1.jpg\" class=\"clubpic\">\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<span>💕동아리 타이틀💕</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<a href=\"clubprelistform.action\">더보기</a> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("<div style=\"text-align: center;\">\r\n");
      out.write("\t<p>회원 모집 동아리</p><br>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t<a href=\"\">\r\n");
      out.write("\t\t\t\t<img src=\"images/pic1.jpg\" class=\"clubpic\">\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<span>💕동아리 타이틀💕</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t<a href=\"\">\r\n");
      out.write("\t\t\t\t<img src=\"images/pic1.jpg\" class=\"clubpic\">\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<span>💕동아리 타이틀💕</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t<a href=\"\">\r\n");
      out.write("\t\t\t\t<img src=\"images/pic1.jpg\" class=\"clubpic\">\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<span>💕동아리 타이틀💕</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<a href=\"\">더보기</a> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /MainPage.jsp(76,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("/nav.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /MainPage.jsp(226,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("footer.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }
}
